version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sentinelrisk-postgres
    environment:
      POSTGRES_DB: sentinelrisk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: sentinelrisk-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HOSTNAME_URL: http://localhost:8081
      KC_HOSTNAME_ADMIN_URL: http://localhost:8081
      KC_HTTP_ENABLED: "true"
      KC_PROXY: passthrough
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - start-dev
      - --http-enabled=true
      - --hostname-strict=false

volumes:
  postgres_data: